config/routes.rb
Rails.application.routes.draw do

  resources :revenues

end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :goods
end

app/models/good.rb
class Good < ActiveRecord::Base

belongs_to :category
end

app/models/item.rb
class Item < ActiveRecord::Base
end

app/models/move.rb
class Move < ActiveRecord::Base
  belongs_to :shop
  belongs_to :store
  

end

app/models/rate.rb
class Rate < ActiveRecord::Base
end

app/models/revenue.rb
class Revenue < ActiveRecord::Base
	belongs_to :shop
	delegate :name, to: :shop, prefix: :shop, allow_nil: false
end

app/models/shop.rb
class Shop < ActiveRecord::Base
	has_many :revenues
end

app/models/store.rb
class Store < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

end

app/controllers/move_controller.rb
class MoveController < ApplicationController

end

app/controllers/revenues_controller.rb
class RevenuesController < ApplicationController
  before_action :set_revenue, only: [:show, :edit, :update, :destroy]

  # GET /revenues
  # GET /revenues.json
  def index
    @revenues = Revenue.all.order('date')
  end

  # GET /revenues/1
  # GET /revenues/1.json
  def show

  end

  # GET /revenues/new
  def new
    @revenue = Revenue.new
  end

  # GET /revenues/1/edit
  def edit
  end

  # POST /revenues
  # POST /revenues.json
  def create

    #@revenue = Revenue.new(revenue_params)
    puts revenue_params
    new_params = revenue_params.except(:money,:salary,:expense)

    @s = true
    REV_TYPE.each do |type|
      var = type[0]
      if revenue_params[:money][var].present?
        puts type[1].to_s+"++++"+revenue_params[:money][var]
        new_params[:retype] = type[1]
        new_params[:number] = revenue_params[:money][var]
        Rails.logger.debug "#{new_params.inspect}"
        @revenue = Revenue.new(new_params)
        @revenue.save

      end

    end
    if revenue_params[:salary].present?
        new_params[:retype] = 2
        new_params[:number] = revenue_params[:salary]
        new_params[:way] = 1
        new_params[:description] = 'salary'
        Rails.logger.debug "#{new_params.inspect}"
        @revenue = Revenue.new(new_params)
        @revenue.save
    end

    respond_to do |format|
      if @s
        format.html { redirect_to revenues_url, notice: 'Revenue was successfully created.' }
        format.json { head :no_content }
      else
        format.html { render :new }
        format.json { render json: @revenue.errors, status: :unprocessable_entity }

      end
    end
  end

  # PATCH/PUT /revenues/1
  # PATCH/PUT /revenues/1.json
  def update
    respond_to do |format|
      if @revenue.update(revenue_params)
        format.html { redirect_to @revenue, notice: 'Revenue was successfully updated.' }
        format.json { render :show, status: :ok, location: @revenue }
      else
        format.html { render :edit }
        format.json { render json: @revenue.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /revenues/1
  # DELETE /revenues/1.json
  def destroy
    @revenue.destroy
    respond_to do |format|
      format.html { redirect_to revenues_url, notice: 'Revenue was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_revenue
      @revenue = Revenue.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def revenue_params
      params[:revenue].permit(:number, :currency, :date, :retype, :shop_id, :way, :salary, :expense, money: [REV_TYPE])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper

	def date_dmY(date)
	  if date.nil?
	    ""
	  else
	    date.strftime("%d/%m/%Y")
	  end
	end
end

app/helpers/move_helper.rb
module MoveHelper
end

app/helpers/revenues_helper.rb
module RevenuesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Buisness</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  
</head>
<body>
<div class="container">
<%= yield %>
</div>
</body>
</html>

app/views/revenues/_form.html.erb
<%= form_for(@revenue) do |f| %>
  <% if @revenue.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@revenue.errors.count, "error") %> prohibited this revenue from being saved:</h2>

      <ul>
      <% @revenue.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <p>
    <%= f.label :shop %><br>
    <%= f.select :shop_id, Shop.all.collect {|x| [x.name, x.id]} %>
  </p>
  <p>
    <%= f.label :date %><br>
    <%= f.text_field :date, :value => date_dmY(@revenue.date) %>
  </p>
  
  <p>
    

    <%= f.label :retype %><br>
    <%= f.select :retype, REV_TYPE, :selected => @revenue.retype %>
  </p>
   <p>

    <%= f.label :number %><br>
    <%= f.select :way, WAY_TYPE, :selected => @revenue.way %>
    <%= f.number_field :number %>
    <%= f.select :currency, CUR_TYPE, :selected => @revenue.currency %>
  </p>
 
  

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/revenues/edit.html.erb
<h1>Editing revenue</h1>

<%= render 'form' %>

<%= link_to 'Show', @revenue %> |
<%= link_to 'Back', revenues_path %>

app/views/revenues/index.html.erb
<h1>BABLo</h1>

<table class="table">
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @revenues.each do |revenue| %>
      <tr class=way<%= revenue.way.to_s%>>
      <td><td><%= REV_TYPE.at(revenue.retype)[2] %></td>
      <td><%= link_to date_dmY(revenue.date), revenue %></td>
      <td><%= revenue.shop_name %></td>
      <td align='right'><%= revenue.number %></td><td><%= CUR_TYPE.at(revenue.currency)[0] %></td>
        <td><%= link_to 'Show', revenue %></td>
        <td><%= link_to 'Edit', edit_revenue_path(revenue) %></td>
        <td><%= link_to 'Destroy', revenue, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Revenue', new_revenue_path %>

app/views/revenues/new.html.erb
  <div class="row">
<h1>New revenue</h1>

<%= form_for(@revenue) do |f| %>

  <% if @revenue.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@revenue.errors.count, "error") %> prohibited this revenue from being saved:</h2>

      <ul>
      <% @revenue.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="form-group">
    <p>
    <%= f.label :shop %><br>
    <%= f.select :shop_id, Shop.all.collect {|x| [x.name, x.id]} %>
  </p>
  <p>

    <%= f.label :date %><br>
    <%= f.text_field :date, :value => date_dmY(@revenue.date)  %>
    <script type="text/javascript">
  $(document).ready(function(){
    $('#revenue_date').datepicker({
      todayHighlight: true,
      todayBtn: true,
      language: "ru",
      autoclose: 'true',
      weekStart: '1'
    });
    $('select').selectpicker();
  });
</script>
  </p>

  <p>
    <%= f.label :retype %><br>
    <%= f.select :currency, CUR_TYPE, :selected => @revenue.currency %>
     <%= f.select :way, WAY_TYPE, :selected => @revenue.way %>
  </p>

</div>
   <p>

    <div class="form-group">
      <%= REV_TYPE.each do |v| %>
      <%= f.label v[2]%><br>
      <%= f.number_field  :number, name: "revenue[money[#{v[0]}]]", :class=>"form-control"  %><br>
      <% end %>
      </div>
        <div class="form-group">

        <%= f.label  "salary" %><br>
    <%= f.number_field  :number, name: "revenue[salary]", :class=>"form-control"  %>
    <br>
    <%= f.label  'expense' %><br>
    <%= f.number_field  :number, name: "revenue[expense]", :class=>"form-control"  %>
  </p>
 </div>

  <div class="actions">
    <%= f.submit :class=>"btn btn-default" %>
  </div>
<% end %>


<%= link_to 'Back', revenues_path %>
 </div>

app/views/revenues/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_revenue_path(@revenue) %> |
<%= link_to 'Back', revenues_path %>

app/views/revenues/test.html.erb
<%= @revs %>